### ISSUE TITLE
support for redhat os_family

### ISSUE THREAD

**Issue by rkoosaar** [r-pufky/ansible_pihole#10]
Hi, 
I was building my own version of ansible pihole role. When doing some research to see if its possible and how others have done it, I stumbled on this. You have done a great job, your work made my own role pointless. 

The only issue I had that this role was built against debian. I myself wanted to use Red Hat os family based distro. 

I've made some modifications, which I tested against my Fedora 37 server and managed to get pihole installed successfully.

changes to install.yml:

```
- name: 'install | install dependencies'
  ansible.builtin.apt:
    name:  '{{ pihole_default_packages }}'
    state: 'latest'
    update_cache: true
  when: 
    - ansible_distribution == 'Debian'

- ansible.builtin.import_tasks: redhat.yml
  when: 
    - ansible_facts['os_family'] == "RedHat"
```
redhat.yml:
```
# Install RPM packages
- name: Ensure a list of RPM packages are installed
  ansible.builtin.dnf:
    name: "{{ pihole_default_packages_rpm }}"
    state: present
  vars:
    pihole_default_packages_rpm:
      - 'git'
      - 'iproute'
      - 'ca-certificates'
      - 'sqlite'
      - 'newt'

- name: set SELINUX to permissive
  ansible.builtin.lineinfile:
    path: /etc/sysconfig/selinux
    regexp: "^SELINUX=enforcing"
    line: "SELINUX=permissive"
    state: present

- name: permit traffic in default zone for pihole services
  ansible.posix.firewalld:
    zone: FedoraServer
    service: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - "http"
    - "dns"
    - "dhcp"
    - "dhcpv6"

- name: create pihole firewalld zone
  ansible.posix.firewalld:
    zone: ftl
    state: present
    permanent: true

- name: add interface lo to flt zone
  ansible.posix.firewalld:
    zone: ftl
    interface: "lo"
    permanent: true
    state: enabled

- name: add interface lo to flt zone
  ansible.posix.firewalld:
    zone: ftl
    port: 4711/tcp
    permanent: true
    state: enabled

- name: reboot
  ansible.builtin.reboot:
    reboot_timeout: 300
    test_command: whoami

```
Maybe you can integrate the support for redhat.yml to your repo?
