### ISSUE TITLE
Docs: Add example usage of `ports` variable

### ISSUE THREAD

**Issue by decoyjoe** [r-pufky/ansible_pihole#13]
In [default/main/ports.yml](https://github.com/r-pufky/ansible_pihole/blob/main/defaults/main/ports.yml) there is a `ports` variable with a list of dictionary items that look to be parameters for the [community.general.ufw](https://docs.ansible.com/ansible/latest/collections/community/general/ufw_module.html) module. There's also a note that says:

> Ports should be managed externally via an OS role.

It would be very helpful to have an example of how one would make use of the `ports` variable items in a playbook or an OS role.

**Comment by r-pufky** [comment]
`ports.yml` is included specifically to define all possible network traffic for the role; it is not intended to be consumed directly, but as a starting point for how you define and manage your firewall. This is intentional as the role does **not** manage firewall services.

You are correct in that the file is defined for the `community.general.ufw` role; I found this to be the most concise way to define network traffic in a consumable way for others; it is defined in this way so anyone using the role can use whatever firewall they are most comfortable with.

Personally, I created a `debian` role I use for my inventory which contains basic configuration options for the OS - I use `community.general.UFW` there to set firewall rules. The key task is:

```yaml
    - name: 'ufw | UFW set additional rules'
      community.general.ufw:
        direction: '{% if "direction" in item %}{{ item.direction }}{% else %}in{% endif %}'
        from_ip:   '{% if "from_ip" in item %}{{ item.from_ip }}{% else %}any{% endif %}'
        from_port: '{% if "from_port" in item %}{{ item.from_port }}{% endif %}'
        to_ip:     '{% if "to_ip" in item %}{{ item.to_ip }}{% else %}any{% endif %}'
        to_port:   '{% if "to_port" in item %}{{ item.to_port }}{% endif %}'
        proto:     '{% if "proto" in item %}{{ item.proto }}{% else %}tcp{% endif %}'
        comment:   '{{ item.comment }}'
        rule:      'allow'
      loop: '{{ ufw_rules }}'
      when: ufw_rules
```

Which loops through the defined rules and whitelists them.
