### ISSUE TITLE
Error during install, as 'pihole' user does not yet exist

### ISSUE THREAD

**Issue by tomhoover** [r-pufky/ansible_pihole#14]
Attempted on Debian 11 (bullseye) & Debian 12 (bookworm)
r-pufky.pihole v3.0.3

This role does not work on a fresh Debian install, as evidenced by the following error message:
```
TASK [r_pufky.pihole : install | set FTL config] **************************************************************************************************************
fatal: [pihole1]: FAILED! => {"changed": false, "checksum": "5a512f2a008e1ebde6b271d75174ad4ee0893165", "gid": 0, "group": "root", "mode": "0644", "msg": "chown failed: failed to look up user pihole", "owner": "root", "path": "/etc/pihole/pihole-FTL.conf", "size": 1485, "state": "file", "uid": 0}
```

Analysis:
The user/group 'pihole' does not exist on a newly installed system, and the above ansible task is called before the pihole user has been created by the pihole installation script.

**Comment by r-pufky** [comment]
Thanks for the report!

This is an ordering issue (setupvars.conf needs to exist before running unattended setup, which creates the pihole user; then the creation/modification of the FTL-DNS configuration can be applied without needing to manually create the pihole user.

Will get something committed today.

**Comment by tomhoover** [comment]
I wasn't familiar enough with pihole's unattended setup to know if simply moving:
```
- name: 'install | set FTL config'
  ansible.builtin.template:
    src: 'pihole-FTL.conf.j2'
    dest: '/etc/pihole/pihole-FTL.conf'
    owner: 'pihole'
    group: 'root'
    mode: 0664 # installed permissions.
  notify: 'restart pihole dns'
```
to follow the setup would cause any problems, so I took the path I did. If moving that task won't hurt anything, I can change my PR to do that instead. Or, I can close my PR request--whatever you prefer.
