### ISSUE TITLE
wrong permissions on /etc/pihole

### ISSUE THREAD

**Issue by marinierb** [r-pufky/ansible_pihole#9]
Ran this role against raspbian running in a virtualbox vm.

I had to change **/etc/pihole** to **775** to be able to add stuff to the whitelist.

Need to fix install.yml?

```
# Pi-Hole will set correct permissions on install and startup.
- name: 'install | create /etc/pihole'
  ansible.builtin.file:
    path:  '/etc/pihole'
    mode:  0755             <-- here?
    state: 'directory'
```
